#Configuracion Sistema POS
#Mon Jun 22 10:45:56 CST 2026
ticket.auto_imprimir=true
db.password=casaos
session.user=luis
ticket.ip_impresora=192.168.100.85
ticket.impresora=
session.pass=MTUxMQ\=\=
telegram.chat_id=ODU5ODIyNDQwOQ\=\=
db.user=root
db.port=3306
db.ip=100.91.90.8
ui.pesta\u00F1a_inicial=VENTAS
db.dump_path=C\:\\Program Files\\MySQL\\MySQL Server 8.0\\bin\\mysqldump.exe
db.name=punto_venta
telegram.token=ODc0MTA2OTQwODpBQUdVQi1qQmJxUEstbUduMzlSYldtOUxkeWFBMnJzbkc3TQ
