#Configuracion General - Sistema POS
#Thu Dec 25 09:21:24 CST 2025
ticket.auto_imprimir=true
db.user=root
db.password=151100
db.port=3306
db.ip=localhost
ticket.impresora=4BARCODE
db.name=punto_venta
