#Configuracion Sistema POS
#Fri Feb 13 20:16:12 CST 2026
ticket.auto_imprimir=false
db.user=root
db.password=casaos
db.port=3306
db.ip=192.168.100.100
ticket.impresora=Adobe PDF
db.dump_path=C\:\\Program Files\\MySQL\\MySQL Server 8.0\\bin\\mysqldump.exe
db.name=punto_venta
